### ISSUE TITLE
App crashes: TypeError: require(...).load is not a function

### ISSUE THREAD

**Issue by ubuntupunk** [andydeforest/note#11]
> node scripts/start-client.js
[1] 
[0] /var/www/virtual/afro/bedrock/web/mix/server.js:1
[0] require('dotenv').load();
[0]                   ^
[0] 
[0] TypeError: require(...).load is not a function
[0]     at Object.<anonymous> (/var/www/virtual/afro/bedrock/web/mix/server.js:1:19)
[0]     at Module._compile (internal/modules/cjs/loader.js:1015:30)
[0]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
[0]     at Module.load (internal/modules/cjs/loader.js:879:32)
[0]     at Function.Module._load (internal/modules/cjs/loader.js:724:14)
[0]     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
[0]     at internal/main/run_main_module.js:17:47

**Comment by ubuntupunk** [comment]
fixed by changing line 1

.load(); >> .config.()
